version: "3.8"

services:
  front:
    build: "../../part1/1.14/front/"
    container_name: frontend
    ports:
      - "127.0.0.1:5000:5000"
  
  back: 
    build: "../../part1/1.14/back/"
    container_name: backend
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - REDIS_HOST=redis-database
      - POSTGRES_HOST=postgres-db
  
  redis:
    image: redis
    restart: unless-stopped
    container_name: redis-database
    ports:
      - "127.0.0.1:6379:6379"
    
  postgres: 
    image: postgres
    restart: unless-stopped
    container_name: postgres-db
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USER=postgres
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/postgresql/data

volumes:
  database: 
